### ISSUE TITLE
Doesn't build on 6.11/6.12

### ISSUE THREAD

**Issue by julianfairfax** [cringeops/bes2600#19]
Log of the build failure:
```
drivers/staging/bes2600/main.c:219:35: error: initialization of 'void (*)(struct ieee80211_hw *, bool)' {aka 'void (*)(struct ieee80211_hw *, _Bool)'} from incompatible pointer type 'void (*)(struct ieee80211_hw *)' [-Wincompatible-pointer-types]
  219 |         .stop                   = bes2600_stop,
      |                                   ^~~~~~~~~~~~
drivers/staging/bes2600/main.c:219:35: note: (near initialization for 'bes2600_ops.stop')
make[8]: *** [scripts/Makefile.build:244: drivers/staging/bes2600/main.o] Error 1
make[7]: *** [scripts/Makefile.build:485: drivers/staging/bes2600] Error 2
make[6]: *** [scripts/Makefile.build:485: drivers/staging] Error 2
make[5]: *** [scripts/Makefile.build:485: drivers] Error 2
make[4]: *** [Makefile:1926: .] Error 2
```

**Comment by julianfairfax** [comment]
The first error can be fixed like this https://github.com/julianfairfax/bes2600/commit/496a0b8860f2a8ef1a4c307e0da55c7bd6a8addf, that leads to another error:
```
drivers/staging/bes2600/ap.c: In function 'bes2600_bss_info_changed':
drivers/staging/bes2600/ap.c:660:76: error: 'struct ieee80211_bss_conf' has no member named 'chandef'; did you mean 'chanreq'?
  660 |                    ch_type = cfg80211_get_chandef_type(&info->chandef);
      |                                                               ^~~~~~~
      |                                                               chanreq
drivers/staging/bes2600/ap.c:971:86: error: 'struct ieee80211_bss_conf' has no member named 'chandef'; did you mean 'chanreq'?
  971 | 80211_channel_type ch_type = cfg80211_get_chandef_type(&info->chandef);
      |                                                               ^~~~~~~
      |                                                               chanreq
drivers/staging/bes2600/ap.c: In function 'bes2600_start_ap':
drivers/staging/bes2600/ap.c:1550:66: error: 'struct ieee80211_bss_conf' has no member named 'chandef'; did you mean 'chanreq'?
 1550 |            .channelMode = (cfg80211_get_chandef_type(&conf->chandef)) << 4,
      |                                                             ^~~~~~~
      |                                                             chanreq
drivers/staging/bes2600/ap.c:1562:82: error: 'struct ieee80211_bss_conf' has no member named 'chandef'; did you mean 'chanreq'?
 1562 | priv->ht_info.channel_type = cfg80211_get_chandef_type(&conf->chandef);
      |                                                               ^~~~~~~
      |                                                               chanreq
make[8]: *** [scripts/Makefile.build:244: drivers/staging/bes2600/ap.o] Error 1
make[7]: *** [scripts/Makefile.build:485: drivers/staging/bes2600] Error 2
make[6]: *** [scripts/Makefile.build:485: drivers/staging] Error 2
make[5]: *** [scripts/Makefile.build:485: drivers] Error 2
make[4]: *** [Makefile:1926: .] Error 2
```

Making the change it says to make https://github.com/julianfairfax/bes2600/commit/7e237d8f27b042abfca22192f450b08edb339f21 leads to this error:
```
drivers/staging/bes2600/ap.c: In function 'bes2600_bss_info_changed':
drivers/staging/bes2600/ap.c:660:69: error: passing argument 1 of 'cfg80211_get_chandef_type' from incompatible pointer type [-Wincompatible-pointer-types]
  660 |                         ch_type = cfg80211_get_chandef_type(&info->chanreq);
      |                                                             ^~~~~~~~~~~~~~
      |                                                             |
      |                                                             struct ieee80211_chan_req *

In file included from ./include/net/mac80211.h:22,
                 from drivers/staging/bes2600/bes2600.h:28,
                 from drivers/staging/bes2600/ap.c:12:
./include/net/cfg80211.h:925:59: note: expected 'const struct cfg80211_chan_def *' but argument is of type 'struct ieee80211_chan_req *'
  925 | cfg80211_get_chandef_type(const struct cfg80211_chan_def *chandef)
      |                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~
drivers/staging/bes2600/ap.c:971:79: error: passing argument 1 of 'cfg80211_get_chandef_type' from incompatible pointer type [-Wincompatible-pointer-types]
  971 | um nl80211_channel_type ch_type = cfg80211_get_chandef_type(&info->chanreq);
      |                                                             ^~~~~~~~~~~~~~
      |                                                             |
      |                                                             struct ieee80211_chan_req *

./include/net/cfg80211.h:925:59: note: expected 'const struct cfg80211_chan_def *' but argument is of type 'struct ieee80211_chan_req *'
  925 | cfg80211_get_chandef_type(const struct cfg80211_chan_def *chandef)
      |                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~
drivers/staging/bes2600/ap.c: In function 'bes2600_start_ap':
drivers/staging/bes2600/ap.c:1550:59: error: passing argument 1 of 'cfg80211_get_chandef_type' from incompatible pointer type [-Wincompatible-pointer-types]
 1550 |                 .channelMode = (cfg80211_get_chandef_type(&conf->chanreq)) << 4,
      |                                                           ^~~~~~~~~~~~~~
      |                                                           |
      |                                                           struct ieee80211_chan_req *
./include/net/cfg80211.h:925:59: note: expected 'const struct cfg80211_chan_def *' but argument is of type 'struct ieee80211_chan_req *'
  925 | cfg80211_get_chandef_type(const struct cfg80211_chan_def *chandef)
      |                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~
drivers/staging/bes2600/ap.c:1562:75: error: passing argument 1 of 'cfg80211_get_chandef_type' from incompatible pointer type [-Wincompatible-pointer-types]
 1562 |   hw_priv->ht_info.channel_type = cfg80211_get_chandef_type(&conf->chanreq);
      |                                                             ^~~~~~~~~~~~~~
      |                                                             |
      |                                                             struct ieee80211_chan_req *

./include/net/cfg80211.h:925:59: note: expected 'const struct cfg80211_chan_def *' but argument is of type 'struct ieee80211_chan_req *'
  925 | cfg80211_get_chandef_type(const struct cfg80211_chan_def *chandef)
      |                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~
make[8]: *** [scripts/Makefile.build:244: drivers/staging/bes2600/ap.o] Error 1
make[7]: *** [scripts/Makefile.build:485: drivers/staging/bes2600] Error 2
make[6]: *** [scripts/Makefile.build:485: drivers/staging] Error 2
make[5]: *** [scripts/Makefile.build:485: drivers] Error 2
make[4]: *** [Makefile:1926: .] Error 2
```

**Comment by julianfairfax** [comment]
Fixed in #20

**Comment by Brt-L** [comment]
Compiled with the fix on kernel 6.13.6.

Also first had to update txrx_opt.c

`483	if (sta->deflink.ht_cap.ht_supported &&`
`484		((priv->vif->bss_conf.chanreq.oper.width == NL80211_CHAN_WIDTH_20 &&`
`                             `^_____________
`485		 sta->deflink.ht_cap.cap & IEEE80211_HT_CAP_SGI_20) ||`
`486		(priv->vif->bss_conf.chanreq.oper.width == NL80211_CHAN_WIDTH_40 &&`
`                             `^_____________
`487		 sta->deflink.ht_cap.cap & IEEE80211_HT_CAP_SGI_40))) {`
`488		bes_devel( "open short gi tx\n");`
`489		bes2600_enable_tx_shortgi(hw_priv, priv, 1);`
